
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - module_30
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: List directory contents
        run: |
              ls -R

      - name: Run unit tests
        run: pytest tests

      - name: Run MyPy type checking
        run: mypy src/

      - name: Run Black formatting check
        run: black --diff --check src/

      - name: Run Isort check
        run: isort --check-only src/

      - name: Run Flake8 linting
        run: flake8 src/
