
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - module_30
  pull_request:
    branches:
      - main
      - module_30
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV
      - name: Verify PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print(sys.path)"

      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: List directory contents
        run: |
              ls -R

      - name: Run unit tests
        run: pytest tests

      - name: Run MyPy type checking
        run: mypy .

      - name: Run Black formatting check
        run: black --diff --check .

      - name: Run Isort check
        run: isort --check-only .

      - name: Run Flake8 linting
        run: flake8 .
