name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  setup:
    uses: ./.github/workflows/setup-python.yml  # Call the reusable workflow
    with:
      python-version: '3.12'  # Specify the Python version

  test:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest tests

  mypy:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MyPy type checking
        run: mypy .

  black:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black formatting check
        run: black --diff --check .

  isort:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Isort check
        run: isort --check-only .

  flake8:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 linting
        run: flake8 .
